name: leap_rigs

dependencies:
- python=3.6
- cudatoolkit=10.1
- cudnn=7.6
- sleap::tensorflow=2.3.1
- pip
- pip:
    - black
    - ipython
    - jupyterlab
    - jedi==0.17.2
    - scipy
    - sklearn
    - matplotlib
    - seaborn
    - "git+https://github.com/murthylab/sleap.git@talmo/supervised_id"
    - "git+https://github.com/loopbio/python-motifapi.git"
    - nidaqmx